SyntaxException: don't print control characters directly
This was causing a small visual problem in the professor's tests that
included CR '\r', which "overwrites" characters printed before it on the
same line.